### ISSUE TITLE
Tracking Reactification

### ISSUE THREAD

**Issue by arialaurel** [saphero/sphero-hack#126]
Primary motivation for switching this to React is that turning the client-side into a SPA is an easy way to stop us from spamming sockets and event listeners on our server-side, which we currently do every time someone navigates to a new page. It will also allow us to keep accelerometer history when the user navigates away from that page.

Here I'm tracking work that needs to be done for this milestone:
#### Components
- [x] Nav
- [ ] Connect
  - [x] Basic Skeleton
  - [ ] Wire up connection logic
- [ ] Move
  - [x] Basic Skeleton
  - [ ] Get graphs working in react
  - [ ] Wire up socket events
- [ ] Color
  - [x] Basic Skeleton
  - [ ] Get color picker working in react
  - [ ] Wire up socket events
- [ ] Presets
  - [ ] Basic Skeleton
  - [ ] Wire up socket events
- [x] About
#### Misc
- [x] Install deps and add build process to gulp
- [x] Serve new build files instead of jade templates
- [x] Fix broken gulp watch task
- [ ] Consolidate statically served files into one place?
- [x] Fix tests
#### Stretch
- [ ] Add React testing
- [ ] Add server side React rendering

**Comment by ghost** [comment]
I like it! I'm going to be looking through the React courses @jessethach sent me, so this would be a fun thing to tackle after the hackathon.

Were you wanting to make this a solo venture or looking for help on tasks?

**Comment by arialaurel** [comment]
I'm game for any help people want to lend! I'm doing it in a reactify branch on the main repo so that anyone on the team can take a look or contribute :smile:

**Comment by xxnatc** [comment]
I'm in! But I do need some time to catch up on the react magic after the hackathon.

**Comment by sabbyt** [comment]
Me too! I've been meaning to add a games section too! 😃

**Comment by jessethach** [comment]
I have some ideas. I can send some PRs for review soon.

**Comment by jessethach** [comment]
@ltegman we can probably turn the `switch` statement from the gamepad.js file into action types in Redux.

**Comment by arialaurel** [comment]
@jessethach Would that be so we could store the button state in redux and use that to highlight the currently pressed button?

**Comment by jessethach** [comment]
@ltegman  Definitely – same could be done with the motion-socket file.

**Comment by arialaurel** [comment]
I've fixed the tests by removing the no longer used (and therefore broken) router tests. Some tests fail when run in gulp because it runs so much slower, so that may be something to look into, but it's not high on my priority list.

**Comment by xxnatc** [comment]
Did someone say React?

**Comment by arialaurel** [comment]
I'm most of the way done with porting the basic skeletons of the pages. Still will need to wire up the actions and handle stuff like graphs and the color picker in react

Thinking about switching to this for color picking: http://casesandberg.github.io/react-color/

Thinking about using this for wiring up all our UI actions that use sockets: https://www.npmjs.com/package/redux-socket.io
